site_name: Knocking's notebook # web page name
theme:
  logo: _assets/icon.png
  favicon: _assets/icon.png
  name: material
  palette:
    primary: brown
    accent: light-blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top # back-to-top button
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
repo_url: https://github.com/CydKnocking/notes
plugins:
  - search
markdown_extensions:
  - tables  
  - pymdownx.betterem
  - pymdownx.arithmatex:
      generic: true  
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences  
  - pymdownx.tabbed:
      alternate_style: true 
  - mdx_truly_sane_lists # fix typora 2 space indentation, ref: https://github.com/mkdocs/mkdocs/issues/545

extra_javascript:
  - _js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  
